import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav>
          <Image alt="" />
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About Us</Link>
        </nav>
      </header>
      <main className={styles.main}>
        <Link href=''>
          <Image alt="" />
          <h2>Events in London</h2>
          <p>
            Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of De Finibus Bonorum et Malorum for use in Link type specimen book. It usually begins with:
          </p>
        </Link>
        <Link href=''>
          <Image alt="" />
          <h2>Events in San Francisco</h2>
          <p>
            Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of De Finibus Bonorum et Malorum for use in Link type specimen book. It usually begins with:
          </p>
        </Link>
        <Link href=''>
          <Image alt="" />
          <h2>Events in Barcelona</h2>
          <p>
            Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of De Finibus Bonorum et Malorum for use in Link type specimen book. It usually begins with:
          </p>
        </Link>
      </main>
      <footer>
        <p>@2023 Time to Code</p>
      </footer>
    </>
  )
}
